version: 2
updates:
  - directory: "/"
    open-pull-requests-limit: 5
    package-ecosystem: "npm"
    rebase-strategy: "auto"
    schedule:
      timezone: "America/Vancouver"
      interval: "daily"
      time: "00:00"
    labels:
      - "security"
      - "react"
    allow:
      - dependency-type: "production"